version: '3.7'
services: 
  backend:
    container_name: backend
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    
  db:
    image: postgres:12
    container_name: database-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db

volumes:
  data: {}